print("What is your first name?")
initial = input()
print("What is your surname?")
surname = input()
print("For how many months do you want your gym membership for?")
months = int(input())
print("Hello,")
print(f"{initial} {surname},")
print("and welcome to your new gym membership with MathGyms Ltd!")
print(f"You have chosen to stay with us for {months} months. Enjoy!")